import type { Permission } from "@prisma/client";

// Cast to Permission so app code can compile before Prisma Client regeneration.
export const CREATE_WORK_ORDERS_FOR_OTHERS = "CREATE_WORK_ORDERS_FOR_OTHERS" as Permission;

// Maintenance feature permissions
export const VIEW_PREVENTATIVE_MAINTENANCE = "VIEW_PREVENTATIVE_MAINTENANCE" as Permission;
export const VIEW_EQUIPMENT_TRACKING = "VIEW_EQUIPMENT_TRACKING" as Permission;
export const VIEW_COMPANY_VEHICLE_LOG = "VIEW_COMPANY_VEHICLE_LOG" as Permission;
export const VIEW_MAINTENANCE_REQUESTS = "VIEW_MAINTENANCE_REQUESTS" as Permission;
export const VIEW_TEMPERATURE_DASHBOARD = "VIEW_TEMPERATURE_DASHBOARD" as Permission;

// Admin feature permissions
export const ADMIN_VIEW_PREVENTATIVE_MAINTENANCE = "ADMIN_VIEW_PREVENTATIVE_MAINTENANCE" as Permission;
export const ADMIN_VIEW_EQUIPMENT_TRACKING = "ADMIN_VIEW_EQUIPMENT_TRACKING" as Permission;
export const ADMIN_VIEW_COMPANY_VEHICLES = "ADMIN_VIEW_COMPANY_VEHICLES" as Permission;
export const ADMIN_VIEW_MAINTENANCE_REQUESTS = "ADMIN_VIEW_MAINTENANCE_REQUESTS" as Permission;
export const ADMIN_VIEW_TEMPERATURE_DASHBOARD = "ADMIN_VIEW_TEMPERATURE_DASHBOARD" as Permission;

// Admin report permissions
export const ADMIN_VIEW_REPORT_SLA_BREACHES = "ADMIN_VIEW_REPORT_SLA_BREACHES" as Permission;
export const ADMIN_VIEW_REPORT_TECHNICIAN_WORKLOAD = "ADMIN_VIEW_REPORT_TECHNICIAN_WORKLOAD" as Permission;
export const ADMIN_VIEW_REPORT_TEMPERATURE_INCIDENTS = "ADMIN_VIEW_REPORT_TEMPERATURE_INCIDENTS" as Permission;
export const ADMIN_VIEW_REPORT_PM_COMPLIANCE = "ADMIN_VIEW_REPORT_PM_COMPLIANCE" as Permission;
export const ADMIN_VIEW_REPORT_PARTS_CONSUMPTION_COSTS = "ADMIN_VIEW_REPORT_PARTS_CONSUMPTION_COSTS" as Permission;
export const ADMIN_VIEW_REPORT_FLEET_TCO = "ADMIN_VIEW_REPORT_FLEET_TCO" as Permission;
export const ADMIN_VIEW_REPORT_PERMISSION_COVERAGE = "ADMIN_VIEW_REPORT_PERMISSION_COVERAGE" as Permission;
export const ADMIN_VIEW_REPORT_NOTIFICATION_EFFECTIVENESS = "ADMIN_VIEW_REPORT_NOTIFICATION_EFFECTIVENESS" as Permission;
