ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'RECEIVE_NOTIFICATION_MAINTENANCE_REQUESTS';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'RECEIVE_NOTIFICATION_TEMPERATURE_ALERTS';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'RECEIVE_NOTIFICATION_WORK_ORDER_SCHEDULES';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'RECEIVE_NOTIFICATION_CYCLE_COUNTS';
