-- Add feature-level permissions for new maintenance/admin modules.
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'VIEW_PREVENTATIVE_MAINTENANCE';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'VIEW_EQUIPMENT_TRACKING';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'VIEW_COMPANY_VEHICLE_LOG';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'VIEW_MAINTENANCE_REQUESTS';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'VIEW_TEMPERATURE_DASHBOARD';

ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'ADMIN_VIEW_PREVENTATIVE_MAINTENANCE';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'ADMIN_VIEW_EQUIPMENT_TRACKING';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'ADMIN_VIEW_COMPANY_VEHICLES';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'ADMIN_VIEW_MAINTENANCE_REQUESTS';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'ADMIN_VIEW_TEMPERATURE_DASHBOARD';
